UPDATE campaigns SET slug = 'uption-kampanya' WHERE id = 11736; -- Was: uption-kampanya-2
UPDATE campaigns SET slug = 'uption-kampanya-uption' WHERE id = 11738; -- Was: uption-kampanya-4
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart' WHERE id = 11739; -- Was: uption-kampanya-5
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-dijital-platform' WHERE id = 11740; -- Was: uption-kampanya-6
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-dijital-platform' WHERE id = 11741; -- Was: uption-kampanya-7
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-sigorta' WHERE id = 11743; -- Was: uption-kampanya-9
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-dijital-platform' WHERE id = 11744; -- Was: uption-kampanya-10
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-e-ticaret' WHERE id = 11746; -- Was: uption-kampanya-12
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-e-ticaret' WHERE id = 11747; -- Was: uption-kampanya-13
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-dijital-platform' WHERE id = 11748; -- Was: uption-kampanya-14
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-dijital-platform' WHERE id = 11749; -- Was: uption-kampanya-15
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-dijital-platform' WHERE id = 11750; -- Was: uption-kampanya-16
UPDATE campaigns SET slug = 'uption-kampanya-uption-uption-kart-finans-yatirim' WHERE id = 11751; -- Was: uption-kampanya-17
UPDATE campaigns SET slug = 'idefix-te-250-tl-indirim' WHERE id = 15875; -- Was: idefix-te-250-tl-indirim-c992530c
UPDATE campaigns SET slug = 'idefix-te-250-tl-indirim-halkbank' WHERE id = 15883; -- Was: idefix-te-250-tl-indirim-8527946e
UPDATE campaigns SET slug = 'house-of-superstep-te-1-000-tl-i-ndirim-ziraat-bankasi' WHERE id = 15137; -- Was: house-of-superstep-te-1-000-tl-i-ndirim-1
UPDATE campaigns SET slug = 'emsanda-pesin-fiyatina-6-aya-varan-taksit-garanti-bbva' WHERE id = 9612; -- Was: emsanda-pesin-fiyatina-6-aya-varan-taksit-2
UPDATE campaigns SET slug = 'emsanda-pesin-fiyatina-6-aya-varan-taksit-garanti-bbva-garanti-bonus' WHERE id = 9782; -- Was: emsanda-pesin-fiyatina-6-aya-varan-taksit-3
UPDATE campaigns SET slug = 'n11-de-pesin-fiyatina-3-taksit-firsati' WHERE id = 14776; -- Was: n11-de-pesin-fiyatina-3-taksit-firsati-d192d5f4
UPDATE campaigns SET slug = 'n11-de-pesin-fiyatina-3-taksit-firsati-halkbank' WHERE id = 14833; -- Was: n11-de-pesin-fiyatina-3-taksit-firsati-9e1f372c
UPDATE campaigns SET slug = 'n11-de-pesin-fiyatina-3-taksit-firsati-halkbank-parafly' WHERE id = 15793; -- Was: n11-de-pesin-fiyatina-3-taksit-firsati-82982b08
UPDATE campaigns SET slug = 'parafly-bireysel-kredi-karti-sahibi-olun-5-000-tl-parafpara-kazanin' WHERE id = 14831; -- Was: parafly-bireysel-kredi-karti-sahibi-olun-5-000-tl-parafpara-kazanin-5dd387bd
UPDATE campaigns SET slug = 'parafly-bireysel-kredi-karti-sahibi-olun-5-000-tl-parafpara-kazanin-halkbank' WHERE id = 15710; -- Was: parafly-bireysel-kredi-karti-sahibi-olun-5-000-tl-parafpara-kazanin-2a12ce01
UPDATE campaigns SET slug = 'elit-optik-te-ilk-1-500-tl-ve-uzeri-gunes-gozlugu-alisverisinize-100-tl-degerinde-parafpara' WHERE id = 11613; -- Was: elit-optik-te-ilk-1-500-tl-ve-uzeri-gunes-gozlugu-alisverisinize-100-tl-degerinde-parafpara-f67149c3
UPDATE campaigns SET slug = 'elit-optik-te-ilk-1-500-tl-ve-uzeri-gunes-gozlugu-alisverisinize-100-tl-degerinde-parafpara-halkbank' WHERE id = 11614; -- Was: elit-optik-te-ilk-1-500-tl-ve-uzeri-gunes-gozlugu-alisverisinize-100-tl-degerinde-parafpara-49ed39df
UPDATE campaigns SET slug = 'occasion-da-4-taksit-garanti-bbva' WHERE id = 9731; -- Was: occasion-da-4-taksit-2
UPDATE campaigns SET slug = 'dailydrive-rent-a-carda-30-indirim-garanti-bbva' WHERE id = 11592; -- Was: dailydrive-rent-a-carda-30-indirim-2
UPDATE campaigns SET slug = 'dailydrive-rent-a-carda-30-indirim-garanti-bbva-garanti-shop-fly' WHERE id = 11596; -- Was: dailydrive-rent-a-carda-30-indirim-3
UPDATE campaigns SET slug = 'club-totalenergiesten-motosiklet-kullanicisi-yeni-uyelere-ozel-25-tl-yakit-puan-ve-5-kat-yakit-puan-hediye-totalenergies' WHERE id = 16754; -- Was: club-totalenergiesten-motosiklet-kullanicisi-yeni-uyelere-ozel-25-tl-yakit-puan-ve-5-kat-yakit-puan-hediye-2
UPDATE campaigns SET slug = 'clubda-yildizlari-toplayin-hediye-kahvenin-tadina-varin-totalenergies' WHERE id = 16752; -- Was: clubda-yildizlari-toplayin-hediye-kahvenin-tadina-varin-2
UPDATE campaigns SET slug = 'sixt-rent-a-carda-35-indirim-garanti-bbva' WHERE id = 9643; -- Was: sixt-rent-a-carda-35-indirim-2
UPDATE campaigns SET slug = 'ipekyol-da-4-taksit-firsati' WHERE id = 14816; -- Was: ipekyol-da-4-taksit-firsati-424c5302
UPDATE campaigns SET slug = 'ipekyol-da-4-taksit-firsati-halkbank' WHERE id = 15765; -- Was: ipekyol-da-4-taksit-firsati-e493a863
UPDATE campaigns SET slug = 'damat-tween-de-2-000-tl-parafpara' WHERE id = 14893; -- Was: damat-tween-de-2-000-tl-parafpara-2d84230c
UPDATE campaigns SET slug = 'damat-tween-de-2-000-tl-parafpara-halkbank' WHERE id = 15780; -- Was: damat-tween-de-2-000-tl-parafpara-99bcfe81
UPDATE campaigns SET slug = 'turkcell-pasajda-pesin-fiyatina-3-taksit-garanti-bbva' WHERE id = 15860; -- Was: turkcell-pasajda-pesin-fiyatina-3-taksit-2
UPDATE campaigns SET slug = 'turkcell-pasajda-pesin-fiyatina-3-taksit-garanti-bbva-garanti-shop-fly' WHERE id = 15869; -- Was: turkcell-pasajda-pesin-fiyatina-3-taksit-3
UPDATE campaigns SET slug = 'biggbrands-yakit-puan-kampanyasi-totalenergies' WHERE id = 16755; -- Was: biggbrands-yakit-puan-kampanyasi-2
UPDATE campaigns SET slug = 'derimod-da-5-taksit-garanti-bbva' WHERE id = 9601; -- Was: derimod-da-5-taksit-2
UPDATE campaigns SET slug = 'puan-harca-yakit-puan-kampanyasi-totalenergies' WHERE id = 16756; -- Was: puan-harca-yakit-puan-kampanyasi-2
UPDATE campaigns SET slug = 'converse-de-4-taksit-garanti-bbva' WHERE id = 9580; -- Was: converse-de-4-taksit-2
UPDATE campaigns SET slug = 'miele-de-pesin-fiyatina-6-taksit-firsati' WHERE id = 14799; -- Was: miele-de-pesin-fiyatina-6-taksit-firsati-f4cac013
UPDATE campaigns SET slug = 'miele-de-pesin-fiyatina-6-taksit-firsati-halkbank' WHERE id = 15756; -- Was: miele-de-pesin-fiyatina-6-taksit-firsati-54ae7e1d
UPDATE campaigns SET slug = 'iwallet-yakit-puan-kampanyasi-totalenergies' WHERE id = 16757; -- Was: iwallet-yakit-puan-kampanyasi-2
UPDATE campaigns SET slug = 'yolcu360tan-garanti-bbvalilara-ozel-yurt-icinde-10-indirim-garanti-bbva' WHERE id = 9198; -- Was: yolcu360tan-garanti-bbvalilara-ozel-yurt-icinde-10-indirim-2
UPDATE campaigns SET slug = 'yolcu360tan-garanti-bbvalilara-ozel-yurt-icinde-10-indirim-garanti-bbva-garanti-bonus' WHERE id = 9572; -- Was: yolcu360tan-garanti-bbvalilara-ozel-yurt-icinde-10-indirim-3
UPDATE campaigns SET slug = 'halkbank-dialog-tan-turkiye-hayat-emeklilik-bireysel-emeklilik-sozlesmesi-baslatanlara-1-500-tl-ye-varan-parafpara' WHERE id = 14884; -- Was: halkbank-dialog-tan-turkiye-hayat-emeklilik-bireysel-emeklilik-sozlesmesi-baslatanlara-1-500-tl-ye-varan-parafpara-b2d27fdd
UPDATE campaigns SET slug = 'halkbank-dialog-tan-turkiye-hayat-emeklilik-bireysel-emeklilik-sozlesmesi-baslatanlara-1-500-tl-ye-varan-parafpara-halkbank' WHERE id = 15746; -- Was: halkbank-dialog-tan-turkiye-hayat-emeklilik-bireysel-emeklilik-sozlesmesi-baslatanlara-1-500-tl-ye-varan-parafpara-b0146d1e
UPDATE campaigns SET slug = 'yeni-uyelere-ozel-10-tl-yakit-puan-hediye-totalenergies' WHERE id = 16758; -- Was: yeni-uyelere-ozel-10-tl-yakit-puan-hediye-2
UPDATE campaigns SET slug = 'intersport-ta-4-taksit-garanti-bbva' WHERE id = 9651; -- Was: intersport-ta-4-taksit-2
UPDATE campaigns SET slug = 'club-totalenergies-ten-dogum-gununuze-ozel-10-tl-yakit-puan-hediye-totalenergies' WHERE id = 16759; -- Was: club-totalenergies-ten-dogum-gununuze-ozel-10-tl-yakit-puan-hediye-2
UPDATE campaigns SET slug = 'toplamda-15000-tlye-varan-worldpuan-odullu-vadaa-sans-hafta-ici-her-aksam-2000de-yapi-kredi' WHERE id = 9537; -- Was: toplamda-15000-tlye-varan-worldpuan-odullu-vadaa-sans-hafta-ici-her-aksam-2000de-2
UPDATE campaigns SET slug = 'yargici-magazalarinda-4-taksit-firsati' WHERE id = 14789; -- Was: yargici-magazalarinda-4-taksit-firsati-5b101c1a
UPDATE campaigns SET slug = 'yargici-magazalarinda-4-taksit-firsati-halkbank' WHERE id = 15750; -- Was: yargici-magazalarinda-4-taksit-firsati-c80b6e53
UPDATE campaigns SET slug = 'secili-e-ticaret-alisverislerinize-2-000-tl-ye-varan-parafpara' WHERE id = 14882; -- Was: secili-e-ticaret-alisverislerinize-2-000-tl-ye-varan-parafpara-b37aaeed
UPDATE campaigns SET slug = 'secili-e-ticaret-alisverislerinize-2-000-tl-ye-varan-parafpara-halkbank' WHERE id = 15728; -- Was: secili-e-ticaret-alisverislerinize-2-000-tl-ye-varan-parafpara-3bab26e5
UPDATE campaigns SET slug = 'beymen-de-6-taksit-garanti-bbva' WHERE id = 9516; -- Was: beymen-de-6-taksit-2
UPDATE campaigns SET slug = 'polariste-pesin-fiyatina-6-aya-varan-taksit-firsati-akbank' WHERE id = 8431; -- Was: polariste-pesin-fiyatina-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'nine-westte-pesin-fiyatina-6-aya-varan-taksit-akbank' WHERE id = 8427; -- Was: nine-westte-pesin-fiyatina-6-aya-varan-taksit-2
UPDATE campaigns SET slug = 'saglik-harcamalariniza-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi' WHERE id = 14783; -- Was: saglik-harcamalariniza-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi-3334e776
UPDATE campaigns SET slug = 'saglik-harcamalariniza-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi-halkbank' WHERE id = 15744; -- Was: saglik-harcamalariniza-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi-4c1d8858
UPDATE campaigns SET slug = 'burberry-de-4-taksit-garanti-bbva' WHERE id = 9559; -- Was: burberry-de-4-taksit-2
UPDATE campaigns SET slug = 'brooks-brothers-ta-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9546; -- Was: brooks-brothers-ta-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'altinyildiz-classics-te-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9448; -- Was: altinyildiz-classics-te-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'minycenter-magazalarinda-4-taksit-firsati' WHERE id = 14873; -- Was: minycenter-magazalarinda-4-taksit-firsati-e1960753
UPDATE campaigns SET slug = 'minycenter-magazalarinda-4-taksit-firsati-halkbank' WHERE id = 15770; -- Was: minycenter-magazalarinda-4-taksit-firsati-ed2f93f6
UPDATE campaigns SET slug = 'bilnet-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati' WHERE id = 14869; -- Was: bilnet-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati-dc2156dc
UPDATE campaigns SET slug = 'bilnet-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati-halkbank' WHERE id = 15722; -- Was: bilnet-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati-8b7c85f6
UPDATE campaigns SET slug = 'barcin-sporda-4-taksit-garanti-bbva' WHERE id = 9482; -- Was: barcin-sporda-4-taksit-2
UPDATE campaigns SET slug = 'ozel-flavius-poliklinigi-nde-estetik-ve-guzellik-hizmetlerinde-20-indirim-ve-pesin-fiyatina-3-taksit' WHERE id = 15517; -- Was: ozel-flavius-poliklinigi-nde-estetik-ve-guzellik-hizmetlerinde-20-indirim-ve-pesin-fiyatina-3-taksit-985911ae
UPDATE campaigns SET slug = 'ozel-flavius-poliklinigi-nde-estetik-ve-guzellik-hizmetlerinde-20-indirim-ve-pesin-fiyatina-3-taksit-halkbank' WHERE id = 15797; -- Was: ozel-flavius-poliklinigi-nde-estetik-ve-guzellik-hizmetlerinde-20-indirim-ve-pesin-fiyatina-3-taksit-d1c72baf
UPDATE campaigns SET slug = 'pazarama-da-pesin-fiyatina-6-taksit' WHERE id = 14838; -- Was: pazarama-da-pesin-fiyatina-6-taksit-9376c108
UPDATE campaigns SET slug = 'pazarama-da-pesin-fiyatina-6-taksit-halkbank' WHERE id = 15796; -- Was: pazarama-da-pesin-fiyatina-6-taksit-e9695ed9
UPDATE campaigns SET slug = 'paraf-uyesi-m-oil-istasyonlarinda-400-tl-parafpara' WHERE id = 14765; -- Was: paraf-uyesi-m-oil-istasyonlarinda-400-tl-parafpara-7a00b0fb
UPDATE campaigns SET slug = 'paraf-uyesi-m-oil-istasyonlarinda-400-tl-parafpara-halkbank' WHERE id = 15733; -- Was: paraf-uyesi-m-oil-istasyonlarinda-400-tl-parafpara-4ad43c64
UPDATE campaigns SET slug = 'pttavm-com-da-pesin-fiyatina-6-aya-varan-taksit-firsati' WHERE id = 14770; -- Was: pttavm-com-da-pesin-fiyatina-6-aya-varan-taksit-firsati-c244d253
UPDATE campaigns SET slug = 'pttavm-com-da-pesin-fiyatina-6-aya-varan-taksit-firsati-halkbank' WHERE id = 14836; -- Was: pttavm-com-da-pesin-fiyatina-6-aya-varan-taksit-firsati-3f7d272e
UPDATE campaigns SET slug = 'pttavm-com-da-pesin-fiyatina-6-aya-varan-taksit-firsati-halkbank-parafly' WHERE id = 15795; -- Was: pttavm-com-da-pesin-fiyatina-6-aya-varan-taksit-firsati-6da68027
UPDATE campaigns SET slug = 'bilfen-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati' WHERE id = 14868; -- Was: bilfen-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati-4f6e6479
UPDATE campaigns SET slug = 'bilfen-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati-halkbank' WHERE id = 15725; -- Was: bilfen-okullarinda-pesin-okul-odemelerinizde-8-taksit-firsati-886c263d
UPDATE campaigns SET slug = 'amazon-com-tr-de-pesin-fiyatina-9-aya-varan-taksit-firsati' WHERE id = 14835; -- Was: amazon-com-tr-de-pesin-fiyatina-9-aya-varan-taksit-firsati-f2619708
UPDATE campaigns SET slug = 'amazon-com-tr-de-pesin-fiyatina-9-aya-varan-taksit-firsati-halkbank' WHERE id = 15794; -- Was: amazon-com-tr-de-pesin-fiyatina-9-aya-varan-taksit-firsati-d72eabaf
UPDATE campaigns SET slug = 'paraflytravel-com-da-ucak-bileti-alisverisine-2500-tl-arac-kiralamaya-5000-tl-ve-otobus-biletinde-50-tl-ye-varan-indirim' WHERE id = 14866; -- Was: paraflytravel-com-da-ucak-bileti-alisverisine-2500-tl-arac-kiralamaya-5000-tl-ve-otobus-biletinde-50-tl-ye-varan-indirim-bd545c07
UPDATE campaigns SET slug = 'paraflytravel-com-da-ucak-bileti-alisverisine-2500-tl-arac-kiralamaya-5000-tl-ve-otobus-biletinde-50-tl-ye-varan-indirim-halkbank' WHERE id = 15792; -- Was: paraflytravel-com-da-ucak-bileti-alisverisine-2500-tl-arac-kiralamaya-5000-tl-ve-otobus-biletinde-50-tl-ye-varan-indirim-64872274
UPDATE campaigns SET slug = 'vakko-da-5-taksit-firsati' WHERE id = 14889; -- Was: vakko-da-5-taksit-firsati-d68ca6dc
UPDATE campaigns SET slug = 'vakko-da-5-taksit-firsati-halkbank' WHERE id = 15789; -- Was: vakko-da-5-taksit-firsati-5bb2c0fe
UPDATE campaigns SET slug = 'monster-notebook-ta-pesin-fiyatina-12-aya-varan-taksit' WHERE id = 14846; -- Was: monster-notebook-ta-pesin-fiyatina-12-aya-varan-taksit-abdfcece
UPDATE campaigns SET slug = 'monster-notebook-ta-pesin-fiyatina-12-aya-varan-taksit-halkbank' WHERE id = 15788; -- Was: monster-notebook-ta-pesin-fiyatina-12-aya-varan-taksit-193b12de
UPDATE campaigns SET slug = 'casper-com-tr-de-pesin-fiyatina-6-taksit' WHERE id = 14786; -- Was: casper-com-tr-de-pesin-fiyatina-6-taksit-7ea869dd
UPDATE campaigns SET slug = 'casper-com-tr-de-pesin-fiyatina-6-taksit-halkbank' WHERE id = 15786; -- Was: casper-com-tr-de-pesin-fiyatina-6-taksit-df992019
UPDATE campaigns SET slug = 'paraf-premium-ve-parafly-a-ozel-ucak-bileti-harcamalariniza-2-500-tl-parafpara' WHERE id = 14779; -- Was: paraf-premium-ve-parafly-a-ozel-ucak-bileti-harcamalariniza-2-500-tl-parafpara-7e3c3b64
UPDATE campaigns SET slug = 'paraf-premium-ve-parafly-a-ozel-ucak-bileti-harcamalariniza-2-500-tl-parafpara-halkbank' WHERE id = 15783; -- Was: paraf-premium-ve-parafly-a-ozel-ucak-bileti-harcamalariniza-2-500-tl-parafpara-fa22cd57
UPDATE campaigns SET slug = 'd-s-damat-ta-1-000-tl-parafpara' WHERE id = 14855; -- Was: d-s-damat-ta-1-000-tl-parafpara-a54d33e7
UPDATE campaigns SET slug = 'd-s-damat-ta-1-000-tl-parafpara-halkbank' WHERE id = 15779; -- Was: d-s-damat-ta-1-000-tl-parafpara-d8e72c5e
UPDATE campaigns SET slug = 'pirelli-de-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9400; -- Was: pirelli-de-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'paraf-troy-kartlara-ozel-secili-sektorlerde-500-tl-parafpara-kampanyasi' WHERE id = 14772; -- Was: paraf-troy-kartlara-ozel-secili-sektorlerde-500-tl-parafpara-kampanyasi-d8a9547c
UPDATE campaigns SET slug = 'paraf-troy-kartlara-ozel-secili-sektorlerde-500-tl-parafpara-kampanyasi-halkbank' WHERE id = 15777; -- Was: paraf-troy-kartlara-ozel-secili-sektorlerde-500-tl-parafpara-kampanyasi-96c40e05
UPDATE campaigns SET slug = 'trendyol-da-pesin-fiyatina-9-aya-varan-taksit' WHERE id = 14769; -- Was: trendyol-da-pesin-fiyatina-9-aya-varan-taksit-e0fb7d51
UPDATE campaigns SET slug = 'trendyol-da-pesin-fiyatina-9-aya-varan-taksit-halkbank' WHERE id = 14864; -- Was: trendyol-da-pesin-fiyatina-9-aya-varan-taksit-a9d2082c
UPDATE campaigns SET slug = 'trendyol-da-pesin-fiyatina-9-aya-varan-taksit-halkbank-parafly' WHERE id = 15798; -- Was: trendyol-da-pesin-fiyatina-9-aya-varan-taksit-96152fd9
UPDATE campaigns SET slug = 'saat-saat-te-pesin-fiyatina-5-taksit' WHERE id = 14853; -- Was: saat-saat-te-pesin-fiyatina-5-taksit-e9287b7c
UPDATE campaigns SET slug = 'saat-saat-te-pesin-fiyatina-5-taksit-halkbank' WHERE id = 15776; -- Was: saat-saat-te-pesin-fiyatina-5-taksit-abcf2e35
UPDATE campaigns SET slug = 'vivense-de-pesin-fiyatina-5-taksit-kampanyasi' WHERE id = 14880; -- Was: vivense-de-pesin-fiyatina-5-taksit-kampanyasi-cbce8018
UPDATE campaigns SET slug = 'vivense-de-pesin-fiyatina-5-taksit-kampanyasi-halkbank' WHERE id = 15773; -- Was: vivense-de-pesin-fiyatina-5-taksit-kampanyasi-ac97f292
UPDATE campaigns SET slug = 'carter-s-magazalarinda-4-taksit-firsati' WHERE id = 14871; -- Was: carter-s-magazalarinda-4-taksit-firsati-0c6ba9b3
UPDATE campaigns SET slug = 'carter-s-magazalarinda-4-taksit-firsati-halkbank' WHERE id = 15771; -- Was: carter-s-magazalarinda-4-taksit-firsati-1d0a7c10
UPDATE campaigns SET slug = 'ikea-da-taksit-kampanyasi' WHERE id = 14862; -- Was: ikea-da-taksit-kampanyasi-f214b0f7
UPDATE campaigns SET slug = 'ikea-da-taksit-kampanyasi-halkbank' WHERE id = 15768; -- Was: ikea-da-taksit-kampanyasi-8ac643cc
UPDATE campaigns SET slug = 'masterpass-e-kayitli-mastercard-sahiplerine-ozel-enuygun-com-mobil-uygulamasinda-gecerli-150-tl-indirim' WHERE id = 14825; -- Was: masterpass-e-kayitli-mastercard-sahiplerine-ozel-enuygun-com-mobil-uygulamasinda-gecerli-150-tl-indirim-29bcd00c
UPDATE campaigns SET slug = 'masterpass-e-kayitli-mastercard-sahiplerine-ozel-enuygun-com-mobil-uygulamasinda-gecerli-150-tl-indirim-halkbank' WHERE id = 15767; -- Was: masterpass-e-kayitli-mastercard-sahiplerine-ozel-enuygun-com-mobil-uygulamasinda-gecerli-150-tl-indirim-f2d279b1
UPDATE campaigns SET slug = 'touristica-com-tr-de-8-500-tl-ye-varan-parafpara-ve-pesin-fiyatina-9-taksit' WHERE id = 14858; -- Was: touristica-com-tr-de-8-500-tl-ye-varan-parafpara-ve-pesin-fiyatina-9-taksit-a4d8c01c
UPDATE campaigns SET slug = 'touristica-com-tr-de-8-500-tl-ye-varan-parafpara-ve-pesin-fiyatina-9-taksit-halkbank' WHERE id = 15784; -- Was: touristica-com-tr-de-8-500-tl-ye-varan-parafpara-ve-pesin-fiyatina-9-taksit-52499399
UPDATE campaigns SET slug = 'sixt-rent-a-car-da-35-indirim-garanti-bbva' WHERE id = 9154; -- Was: sixt-rent-a-car-da-35-indirim-2
UPDATE campaigns SET slug = 'ramsey-de-5-taksit-firsati' WHERE id = 14805; -- Was: ramsey-de-5-taksit-firsati-c7b1883e
UPDATE campaigns SET slug = 'ramsey-de-5-taksit-firsati-halkbank' WHERE id = 15760; -- Was: ramsey-de-5-taksit-firsati-63935377
UPDATE campaigns SET slug = 'columbiada-9-aya-varan-taksit-firsati-akbank' WHERE id = 8326; -- Was: columbiada-9-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'itopya-com-da-vade-farksiz-6-taksit' WHERE id = 16412; -- Was: itopya-com-da-vade-farksiz-6-taksit-b2f837d9
UPDATE campaigns SET slug = 'itopya-com-da-vade-farksiz-6-taksit-halkbank' WHERE id = 16413; -- Was: itopya-com-da-vade-farksiz-6-taksit-4149cd4c
UPDATE campaigns SET slug = 'ki-p-te-5-taksit-firsati' WHERE id = 14807; -- Was: ki-p-te-5-taksit-firsati-67b8e653
UPDATE campaigns SET slug = 'ki-p-te-5-taksit-firsati-halkbank' WHERE id = 15758; -- Was: ki-p-te-5-taksit-firsati-b5f5f7ab
UPDATE campaigns SET slug = 'divarese-de-4-taksit-firsati' WHERE id = 14793; -- Was: divarese-de-4-taksit-firsati-60013e12
UPDATE campaigns SET slug = 'divarese-de-4-taksit-firsati-halkbank' WHERE id = 15751; -- Was: divarese-de-4-taksit-firsati-e433180b
UPDATE campaigns SET slug = 'beymende-6-taksit-garanti-bbva' WHERE id = 8992; -- Was: beymende-6-taksit-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-apple-ve-microsoft-platformlarindan-yapacaginiz-harcamalara' WHERE id = 16416; -- Was: mastercard-logolu-asil-kartiniz-ile-apple-ve-microsoft-platformlarindan-yapacaginiz-harcamalara-2026
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-apple-ve-microsoft-platformlarindan-yapacaginiz-harcamalara-yapi-kredi' WHERE id = 16420; -- Was: mastercard-logolu-asil-kartiniz-ile-apple-ve-microsoft-platformlarindan-yapacaginiz-harcamalara-2026-2
UPDATE campaigns SET slug = 'ayakkabi-dunyasinda-6-aya-varan-taksit-firsati-akbank' WHERE id = 8183; -- Was: ayakkabi-dunyasinda-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'giyim-ve-kozmetik-alisverislerinize-2-000-tl-parafpara' WHERE id = 14757; -- Was: giyim-ve-kozmetik-alisverislerinize-2-000-tl-parafpara-7283faad
UPDATE campaigns SET slug = 'giyim-ve-kozmetik-alisverislerinize-2-000-tl-parafpara-halkbank' WHERE id = 15738; -- Was: giyim-ve-kozmetik-alisverislerinize-2-000-tl-parafpara-3be86bdd
UPDATE campaigns SET slug = 'paraf-uyesi-totalenergies-istasyonlarinda-400-tl-parafpara' WHERE id = 14768; -- Was: paraf-uyesi-totalenergies-istasyonlarinda-400-tl-parafpara-f6bcd837
UPDATE campaigns SET slug = 'paraf-uyesi-totalenergies-istasyonlarinda-400-tl-parafpara-halkbank' WHERE id = 15736; -- Was: paraf-uyesi-totalenergies-istasyonlarinda-400-tl-parafpara-3dc6ab7b
UPDATE campaigns SET slug = 'elektrikli-arac-sarj-istasyonu-harcamalariniza-200-tl-parafpara' WHERE id = 14756; -- Was: elektrikli-arac-sarj-istasyonu-harcamalariniza-200-tl-parafpara-d6f248c2
UPDATE campaigns SET slug = 'elektrikli-arac-sarj-istasyonu-harcamalariniza-200-tl-parafpara-halkbank' WHERE id = 15735; -- Was: elektrikli-arac-sarj-istasyonu-harcamalariniza-200-tl-parafpara-85a1f638
UPDATE campaigns SET slug = 'macfit-te-1-000-tl-maxipuan-i-sbankasi' WHERE id = 15727; -- Was: macfit-te-1-000-tl-maxipuan-1
UPDATE campaigns SET slug = 'mobilya-dekorasyon-ve-yapi-marketi-alisverislerinize-3-000-tl-ye-varan-parafpara' WHERE id = 14760; -- Was: mobilya-dekorasyon-ve-yapi-marketi-alisverislerinize-3-000-tl-ye-varan-parafpara-80159515
UPDATE campaigns SET slug = 'mobilya-dekorasyon-ve-yapi-marketi-alisverislerinize-3-000-tl-ye-varan-parafpara-halkbank' WHERE id = 15719; -- Was: mobilya-dekorasyon-ve-yapi-marketi-alisverislerinize-3-000-tl-ye-varan-parafpara-8cce7f00
UPDATE campaigns SET slug = 'seyahat-konaklama-ve-arac-kiralama-harcamalariniza-3-000-tl-ye-varan-parafpara' WHERE id = 14754; -- Was: seyahat-konaklama-ve-arac-kiralama-harcamalariniza-3-000-tl-ye-varan-parafpara-11ead52b
UPDATE campaigns SET slug = 'seyahat-konaklama-ve-arac-kiralama-harcamalariniza-3-000-tl-ye-varan-parafpara-halkbank' WHERE id = 15714; -- Was: seyahat-konaklama-ve-arac-kiralama-harcamalariniza-3-000-tl-ye-varan-parafpara-770e046c
UPDATE campaigns SET slug = 'adv-magazalarinda-750-tl-parafpara-firsati' WHERE id = 14891; -- Was: adv-magazalarinda-750-tl-parafpara-firsati-37769574
UPDATE campaigns SET slug = 'adv-magazalarinda-750-tl-parafpara-firsati-halkbank' WHERE id = 15790; -- Was: adv-magazalarinda-750-tl-parafpara-firsati-9e2e9eb7
UPDATE campaigns SET slug = 'cacharelde-6-taksit-garanti-bbva' WHERE id = 9011; -- Was: cacharelde-6-taksit-2
UPDATE campaigns SET slug = 'a101de-pesin-fiyatina-6-aya-varan-taksit-garanti-bbva' WHERE id = 15481; -- Was: a101de-pesin-fiyatina-6-aya-varan-taksit-2
UPDATE campaigns SET slug = 'a101de-pesin-fiyatina-6-aya-varan-taksit-garanti-bbva-garanti-bonus' WHERE id = 15686; -- Was: a101de-pesin-fiyatina-6-aya-varan-taksit-3
UPDATE campaigns SET slug = 'germencik-organik-pazar-da-11-i-ndirim' WHERE id = 14886; -- Was: germencik-organik-pazar-da-11-i-ndirim-0044cca2
UPDATE campaigns SET slug = 'germencik-organik-pazar-da-11-i-ndirim-halkbank' WHERE id = 15791; -- Was: germencik-organik-pazar-da-11-i-ndirim-54518835
UPDATE campaigns SET slug = '1-000-000-tl-5-000-000-tl-arasi-dijital-gib-gov-tr-den-yapilan-gelir-vergisi-odemelerinize-2-taksit-garanti-bbva' WHERE id = 15473; -- Was: 1-000-000-tl-5-000-000-tl-arasi-dijital-gib-gov-tr-den-yapilan-gelir-vergisi-odemelerinize-2-taksit-2
UPDATE campaigns SET slug = 'giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan' WHERE id = 15971; -- Was: giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan-2026
UPDATE campaigns SET slug = 'giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan-yapi-kredi' WHERE id = 15975; -- Was: giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan-2026-2
UPDATE campaigns SET slug = 'giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan-yapi-kredi-world' WHERE id = 15985; -- Was: giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan-2026-3
UPDATE campaigns SET slug = 'giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan-yapi-kredi-play' WHERE id = 16132; -- Was: giyim-ve-kozmetik-sektorunde-yapacagin-ilk-3000-tl-ve-uzeri-harcamadan-sonraki-her-3000-t-nisan-2026-4
UPDATE campaigns SET slug = 'vakkoda-pesin-fiyatina-6-taksit-yapi-kredi' WHERE id = 15980; -- Was: vakkoda-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'paraf-troy-ile-usak-ta-hafta-ici-her-gun-ilk-ulasimin-ucretsiz' WHERE id = 15945; -- Was: paraf-troy-ile-usak-ta-hafta-ici-her-gun-ilk-ulasimin-ucretsiz-1411761d
UPDATE campaigns SET slug = 'paraf-troy-ile-usak-ta-hafta-ici-her-gun-ilk-ulasimin-ucretsiz-halkbank' WHERE id = 15957; -- Was: paraf-troy-ile-usak-ta-hafta-ici-her-gun-ilk-ulasimin-ucretsiz-6e644a3f
UPDATE campaigns SET slug = 'carrefoursada-pesin-fiyatina-5-aya-varan-taksit-garanti-bbva' WHERE id = 15673; -- Was: carrefoursada-pesin-fiyatina-5-aya-varan-taksit-2
UPDATE campaigns SET slug = 'gurgencler-de-pesin-fiyatina-6-taksit' WHERE id = 14818; -- Was: gurgencler-de-pesin-fiyatina-6-taksit-9ebeb3e4
UPDATE campaigns SET slug = 'gurgencler-de-pesin-fiyatina-6-taksit-halkbank' WHERE id = 15775; -- Was: gurgencler-de-pesin-fiyatina-6-taksit-664eca9a
UPDATE campaigns SET slug = 'twist-te-4-taksit-firsati' WHERE id = 14582; -- Was: twist-te-4-taksit-firsati-ac0fa9cd
UPDATE campaigns SET slug = 'twist-te-4-taksit-firsati-halkbank' WHERE id = 14814; -- Was: twist-te-4-taksit-firsati-a474f847
UPDATE campaigns SET slug = 'twist-te-4-taksit-firsati-halkbank-parafly' WHERE id = 15764; -- Was: twist-te-4-taksit-firsati-1db43ef7
UPDATE campaigns SET slug = 'armagan-oyuncak-ta-4-taksit-garanti-bbva' WHERE id = 9368; -- Was: armagan-oyuncak-ta-4-taksit-2
UPDATE campaigns SET slug = 'alarko-carrierda-pesin-fiyatina-9-taksit-garanti-bbva' WHERE id = 15484; -- Was: alarko-carrierda-pesin-fiyatina-9-taksit-2
UPDATE campaigns SET slug = 'alarko-carrierda-pesin-fiyatina-9-taksit-garanti-bbva-garanti-bonus' WHERE id = 15662; -- Was: alarko-carrierda-pesin-fiyatina-9-taksit-3
UPDATE campaigns SET slug = 'hepsiburada-da-pesin-fiyatina-6-aya-varan-taksit-firsati' WHERE id = 14773; -- Was: hepsiburada-da-pesin-fiyatina-6-aya-varan-taksit-firsati-9a6a00f6
UPDATE campaigns SET slug = 'hepsiburada-da-pesin-fiyatina-6-aya-varan-taksit-firsati-halkbank' WHERE id = 14813; -- Was: hepsiburada-da-pesin-fiyatina-6-aya-varan-taksit-firsati-a49513b0
UPDATE campaigns SET slug = 'hepsiburada-da-pesin-fiyatina-6-aya-varan-taksit-firsati-halkbank-parafly' WHERE id = 15769; -- Was: hepsiburada-da-pesin-fiyatina-6-aya-varan-taksit-firsati-02f02b39
UPDATE campaigns SET slug = 'oxxo-da-4-taksit-firsati' WHERE id = 14811; -- Was: oxxo-da-4-taksit-firsati-753b79d1
UPDATE campaigns SET slug = 'oxxo-da-4-taksit-firsati-halkbank' WHERE id = 15762; -- Was: oxxo-da-4-taksit-firsati-cdb39090
UPDATE campaigns SET slug = 'dyson-da-pesin-fiyatina-9-aya-varan-taksit' WHERE id = 14809; -- Was: dyson-da-pesin-fiyatina-9-aya-varan-taksit-d9ea134a
UPDATE campaigns SET slug = 'dyson-da-pesin-fiyatina-9-aya-varan-taksit-halkbank' WHERE id = 15761; -- Was: dyson-da-pesin-fiyatina-9-aya-varan-taksit-6bad11a8
UPDATE campaigns SET slug = 'trendyol-go-by-uber-eatsten-yemek-siparisinize-ek-20-indirim-garanti-bbva' WHERE id = 15865; -- Was: trendyol-go-by-uber-eatsten-yemek-siparisinize-ek-20-indirim-2
UPDATE campaigns SET slug = 'a101-de-pesin-fiyatina-6-aya-varan-taksit' WHERE id = 14803; -- Was: a101-de-pesin-fiyatina-6-aya-varan-taksit-c533dc26
UPDATE campaigns SET slug = 'a101-de-pesin-fiyatina-6-aya-varan-taksit-halkbank' WHERE id = 15742; -- Was: a101-de-pesin-fiyatina-6-aya-varan-taksit-6414dc78
UPDATE campaigns SET slug = 'egitim-sektorunde-5-taksit' WHERE id = 14801; -- Was: egitim-sektorunde-5-taksit-c0019f16
UPDATE campaigns SET slug = 'egitim-sektorunde-5-taksit-halkbank' WHERE id = 15785; -- Was: egitim-sektorunde-5-taksit-9883c2ff
UPDATE campaigns SET slug = 'network-te-4-taksit-firsati' WHERE id = 14796; -- Was: network-te-4-taksit-firsati-7976e6ff
UPDATE campaigns SET slug = 'network-te-4-taksit-firsati-halkbank' WHERE id = 15753; -- Was: network-te-4-taksit-firsati-a7752c37
UPDATE campaigns SET slug = 'i-gdas-fatura-odemelerinde-vade-farksiz-6-taksit' WHERE id = 11095; -- Was: i-gdas-fatura-odemelerinde-vade-farksiz-6-taksit-8749a7ae
UPDATE campaigns SET slug = 'i-gdas-fatura-odemelerinde-vade-farksiz-6-taksit-halkbank' WHERE id = 11097; -- Was: i-gdas-fatura-odemelerinde-vade-farksiz-6-taksit-b880af27
UPDATE campaigns SET slug = 'jolly-de-vade-farksiz-9-taksit-garanti-bbva' WHERE id = 11036; -- Was: jolly-de-vade-farksiz-9-taksit-2
UPDATE campaigns SET slug = 'vergi-ve-sigorta-odemelerinize-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi' WHERE id = 14784; -- Was: vergi-ve-sigorta-odemelerinize-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi-f3cac0e0
UPDATE campaigns SET slug = 'vergi-ve-sigorta-odemelerinize-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi-halkbank' WHERE id = 15748; -- Was: vergi-ve-sigorta-odemelerinize-4-aya-varan-faizsiz-sonradan-taksit-kampanyasi-a235950c
UPDATE campaigns SET slug = 'qcar-mobilite-de-arac-kiralamalarda-40-indirim-ve-5-taksit-firsati-garanti-bbva' WHERE id = 15573; -- Was: qcar-mobilite-de-arac-kiralamalarda-40-indirim-ve-5-taksit-firsati-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yapacaginiz-yurt-disi-online-alisverislerde-250-tl-pua-mart' WHERE id = 12543; -- Was: mastercard-logolu-asil-kartiniz-ile-yapacaginiz-yurt-disi-online-alisverislerde-250-tl-pua-mart-2026
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yapacaginiz-yurt-disi-online-alisverislerde-250-tl-pua-mart-yapi-kredi' WHERE id = 12551; -- Was: mastercard-logolu-asil-kartiniz-ile-yapacaginiz-yurt-disi-online-alisverislerde-250-tl-pua-mart-2026-2
UPDATE campaigns SET slug = 'totalenergies-istasyonlarinda-yakit-garantisi-ile-renault-nuz-guvende-totalenergies' WHERE id = 16886; -- Was: totalenergies-istasyonlarinda-yakit-garantisi-ile-renault-nuz-guvende-2
UPDATE campaigns SET slug = 'turk-hava-yollari-nda-6-ya-varan-taksit-firsati' WHERE id = 9779; -- Was: turk-hava-yollari-nda-6-ya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'turk-hava-yollari-nda-6-ya-varan-taksit-firsati-i-sbankasi' WHERE id = 14778; -- Was: turk-hava-yollari-nda-6-ya-varan-taksit-firsati
UPDATE campaigns SET slug = 'akinal-bella-da-1-000-tl-ve-uzeri-alisverise-20-indirim-garanti-bbva' WHERE id = 15445; -- Was: akinal-bella-da-1-000-tl-ve-uzeri-alisverise-20-indirim-2
UPDATE campaigns SET slug = 'pumada-6-taksit-garanti-bbva' WHERE id = 9992; -- Was: pumada-6-taksit-2
UPDATE campaigns SET slug = 'otomatik-fatura-odeme-talimatlariniza-1-000-tl-ye-varan-parafpara' WHERE id = 14823; -- Was: otomatik-fatura-odeme-talimatlariniza-1-000-tl-ye-varan-parafpara-602b1412
UPDATE campaigns SET slug = 'otomatik-fatura-odeme-talimatlariniza-1-000-tl-ye-varan-parafpara-halkbank' WHERE id = 15787; -- Was: otomatik-fatura-odeme-talimatlariniza-1-000-tl-ye-varan-parafpara-585071d7
UPDATE campaigns SET slug = 'vaillant-da-9-aya-varan-taksit-ve-3000-tl-parafpara' WHERE id = 15704; -- Was: vaillant-da-9-aya-varan-taksit-ve-3000-tl-parafpara-36ed0d24
UPDATE campaigns SET slug = 'vaillant-da-9-aya-varan-taksit-ve-3000-tl-parafpara-halkbank' WHERE id = 15781; -- Was: vaillant-da-9-aya-varan-taksit-ve-3000-tl-parafpara-d4b7c5d5
UPDATE campaigns SET slug = 'paraflytravel-com-da-15-000-tl-ye-varan-indirim-kodu-veya-pesin-odemede-10-indirim' WHERE id = 14848; -- Was: paraflytravel-com-da-15-000-tl-ye-varan-indirim-kodu-veya-pesin-odemede-10-indirim-db7125e5
UPDATE campaigns SET slug = 'paraflytravel-com-da-15-000-tl-ye-varan-indirim-kodu-veya-pesin-odemede-10-indirim-halkbank' WHERE id = 15774; -- Was: paraflytravel-com-da-15-000-tl-ye-varan-indirim-kodu-veya-pesin-odemede-10-indirim-dc546d75
UPDATE campaigns SET slug = 'pierre-cardin-de-6-taksit-garanti-bbva' WHERE id = 9742; -- Was: pierre-cardin-de-6-taksit-2
UPDATE campaigns SET slug = 'secili-okullarda-yapacaginiz-pesin-okul-odemelerinize-ucretsiz-3-taksit-garanti-bbva' WHERE id = 15494; -- Was: secili-okullarda-yapacaginiz-pesin-okul-odemelerinize-ucretsiz-3-taksit-2
UPDATE campaigns SET slug = 'secili-okullarda-yapacaginiz-pesin-okul-odemelerinize-ucretsiz-3-taksit-garanti-bbva-garanti-miles-smiles' WHERE id = 15558; -- Was: secili-okullarda-yapacaginiz-pesin-okul-odemelerinize-ucretsiz-3-taksit-3
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yabanci-dizi-ve-film-platformlarindan-yapacaginiz-harc-mart' WHERE id = 12562; -- Was: mastercard-logolu-asil-kartiniz-ile-yabanci-dizi-ve-film-platformlarindan-yapacaginiz-harc-mart-2026
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yabanci-dizi-ve-film-platformlarindan-yapacaginiz-harc-mart-yapi-kredi' WHERE id = 16418; -- Was: mastercard-logolu-asil-kartiniz-ile-yabanci-dizi-ve-film-platformlarindan-yapacaginiz-harc-mart-2026-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yabanci-dizi-ve-film-platformlarindan-yapacaginiz-harc-mart-yapi-kredi-crystal' WHERE id = 16421; -- Was: mastercard-logolu-asil-kartiniz-ile-yabanci-dizi-ve-film-platformlarindan-yapacaginiz-harc-mart-2026-3
UPDATE campaigns SET slug = 'mielede-pesin-fiyatina-8-aya-varan-taksit-firsati-akbank' WHERE id = 8357; -- Was: mielede-pesin-fiyatina-8-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'king-den-50-indirim-ve-1-250-ye-varan-yakit-puan-totalenergies' WHERE id = 16881; -- Was: king-den-50-indirim-ve-1-250-ye-varan-yakit-puan-2
UPDATE campaigns SET slug = 'yann-tiersen-konser-biletleri-maximum-kart-lara-10-i-ndirimli-i-sbankasi' WHERE id = 10887; -- Was: yann-tiersen-konser-biletleri-maximum-kart-lara-10-i-ndirimli-1
UPDATE campaigns SET slug = 'pazarama-da-pesin-fiyatina-6-aya-varan-taksit-garanti-bbva' WHERE id = 16179; -- Was: pazarama-da-pesin-fiyatina-6-aya-varan-taksit-2
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-sabiha-gokcen-havalimaninda-ucretsiz-allways-fast-trackhizli-geci-yapi-kredi' WHERE id = 14959; -- Was: silver-logolu-mastercardiniza-ozel-sabiha-gokcen-havalimaninda-ucretsiz-allways-fast-trackhizli-geci-2
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-sabiha-gokcen-havalimaninda-ucretsiz-allways-fast-trackhizli-geci-yapi-kredi-world' WHERE id = 14974; -- Was: silver-logolu-mastercardiniza-ozel-sabiha-gokcen-havalimaninda-ucretsiz-allways-fast-trackhizli-geci-3
UPDATE campaigns SET slug = 'vestel-de-9-aya-varan-taksit-firsati' WHERE id = 14887; -- Was: vestel-de-9-aya-varan-taksit-firsati-71cd4f03
UPDATE campaigns SET slug = 'vestel-de-9-aya-varan-taksit-firsati-halkbank' WHERE id = 15755; -- Was: vestel-de-9-aya-varan-taksit-firsati-0c9dfbfb
UPDATE campaigns SET slug = 'pancoda-4-taksit-garanti-bbva' WHERE id = 9374; -- Was: pancoda-4-taksit-2
UPDATE campaigns SET slug = 'pancoda-4-taksit-garanti-bbva-garanti-shop-fly' WHERE id = 9396; -- Was: pancoda-4-taksit-3
UPDATE campaigns SET slug = 'pancoda-4-taksit-garanti-bbva-garanti-bonus' WHERE id = 9802; -- Was: pancoda-4-taksit-4
UPDATE campaigns SET slug = 'baymakta-12-taksit-garanti-bbva' WHERE id = 16537; -- Was: baymakta-12-taksit-2
UPDATE campaigns SET slug = 'baymakta-12-taksit-garanti-bbva-garanti-bonus' WHERE id = 16780; -- Was: baymakta-12-taksit-3
UPDATE campaigns SET slug = 'nissan-yetkili-servis-noktalarinda-6-aya-varan-taksit-garanti-bbva' WHERE id = 15583; -- Was: nissan-yetkili-servis-noktalarinda-6-aya-varan-taksit-2
UPDATE campaigns SET slug = 'nissan-yetkili-servis-noktalarinda-6-aya-varan-taksit-garanti-bbva-garanti-bonus' WHERE id = 15706; -- Was: nissan-yetkili-servis-noktalarinda-6-aya-varan-taksit-3
UPDATE campaigns SET slug = 'ecrouda-pesin-fiyatina-6-aya-varan-taksit-firsati-akbank' WHERE id = 8411; -- Was: ecrouda-pesin-fiyatina-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'floda-pesin-fiyatina-6-aya-varan-taksit-firsati-akbank' WHERE id = 8413; -- Was: floda-pesin-fiyatina-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'hotel-anatolia-da-konaklamada-pesin-fiyatina-10-indirim-garanti-bbva' WHERE id = 9176; -- Was: hotel-anatolia-da-konaklamada-pesin-fiyatina-10-indirim-2
UPDATE campaigns SET slug = 'lastikcim-com-da-secili-goodyear-lastik-alisverisinizde-2-500-tl-ye-varan-parafpara-ve-5-taksit-firsati' WHERE id = 16642; -- Was: lastikcim-com-da-secili-goodyear-lastik-alisverisinizde-2-500-tl-ye-varan-parafpara-ve-5-taksit-firsati-54c62853
UPDATE campaigns SET slug = 'lastikcim-com-da-secili-goodyear-lastik-alisverisinizde-2-500-tl-ye-varan-parafpara-ve-5-taksit-firsati-halkbank' WHERE id = 16644; -- Was: lastikcim-com-da-secili-goodyear-lastik-alisverisinizde-2-500-tl-ye-varan-parafpara-ve-5-taksit-firsati-e459b1d4
UPDATE campaigns SET slug = 'samsoniteta-6-aya-varan-taksit-firsati-akbank' WHERE id = 8417; -- Was: samsoniteta-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'market-al-veri-lerinize-1-000-tl-bankkart-lira-ziraat-bankasi' WHERE id = 16555; -- Was: market-al-veri-lerinize-1-000-tl-bankkart-lira-1
UPDATE campaigns SET slug = 'saat-saat-te-pesin-fiyatina-6-taksit' WHERE id = 10251; -- Was: saat-saat-te-pesin-fiyatina-6-taksit-f3b7e628
UPDATE campaigns SET slug = 'saat-saat-te-pesin-fiyatina-6-taksit-halkbank' WHERE id = 11094; -- Was: saat-saat-te-pesin-fiyatina-6-taksit-e75b4823
UPDATE campaigns SET slug = 'reebok-com-trde-4-000-tl-uzeri-alisverise-1-000-tl-indirim' WHERE id = 14222; -- Was: reebok-com-trde-4-000-tl-uzeri-alisverise-1-000-tl-indirim-2
UPDATE campaigns SET slug = 'reebok-com-trde-4-000-tl-uzeri-alisverise-1-000-tl-indirim-akbank' WHERE id = 14689; -- Was: reebok-com-trde-4-000-tl-uzeri-alisverise-1-000-tl-indirim
UPDATE campaigns SET slug = 'pierre-cardinde-6-taksit-garanti-bbva' WHERE id = 8999; -- Was: pierre-cardinde-6-taksit-2
UPDATE campaigns SET slug = 'alfemo-da-pesin-fiyatina-8-taksit' WHERE id = 10016; -- Was: alfemo-da-pesin-fiyatina-8-taksit-233334d0
UPDATE campaigns SET slug = 'alfemo-da-pesin-fiyatina-8-taksit-halkbank' WHERE id = 10218; -- Was: alfemo-da-pesin-fiyatina-8-taksit-80c6e7b3
UPDATE campaigns SET slug = 'brooks-brothers-ta-20-000-tl-ve-uzerine-tum-indirimlere-ek-10-indirim-garanti-bbva' WHERE id = 16534; -- Was: brooks-brothers-ta-20-000-tl-ve-uzerine-tum-indirimlere-ek-10-indirim-2
UPDATE campaigns SET slug = 'damat-tween-de-6-aya-varan-taksit-firsati' WHERE id = 9439; -- Was: damat-tween-de-6-aya-varan-taksit-firsati-4fcfb2e0
UPDATE campaigns SET slug = 'damat-tween-de-6-aya-varan-taksit-firsati-halkbank' WHERE id = 10127; -- Was: damat-tween-de-6-aya-varan-taksit-firsati-29a8c4cc
UPDATE campaigns SET slug = 'porland-da-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 15548; -- Was: porland-da-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'my-visa-uyelerine-avrupa-ve-amerika-da-taksi-ve-ozel-arac-yolculuklarinda-nakit-iade-firsati-garanti-bbva' WHERE id = 9640; -- Was: my-visa-uyelerine-avrupa-ve-amerika-da-taksi-ve-ozel-arac-yolculuklarinda-nakit-iade-firsati-2
UPDATE campaigns SET slug = 'n11-de-pesin-fiyatina-6-aya-varan-taksit-garanti-bbva' WHERE id = 15543; -- Was: n11-de-pesin-fiyatina-6-aya-varan-taksit-2
UPDATE campaigns SET slug = 'bauhaus-da-vade-farksiz-6-taksit-garanti-bbva' WHERE id = 15492; -- Was: bauhaus-da-vade-farksiz-6-taksit-2
UPDATE campaigns SET slug = 'emlak-ve-cevre-temizlik-vergisi-odemelerinize-ucretsiz-4-e-varan-taksit' WHERE id = 8923; -- Was: emlak-ve-cevre-temizlik-vergisi-odemelerinize-ucretsiz-4-e-varan-taksit-c91158cf
UPDATE campaigns SET slug = 'emlak-ve-cevre-temizlik-vergisi-odemelerinize-ucretsiz-4-e-varan-taksit-halkbank' WHERE id = 10066; -- Was: emlak-ve-cevre-temizlik-vergisi-odemelerinize-ucretsiz-4-e-varan-taksit-868bd703
UPDATE campaigns SET slug = 'migros-ta-elektronik-urunlerinde-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 15533; -- Was: migros-ta-elektronik-urunlerinde-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'paraf-platinum-ve-parafly-platinum-dan-amazon-prime-uyeligi-hediye' WHERE id = 9120; -- Was: paraf-platinum-ve-parafly-platinum-dan-amazon-prime-uyeligi-hediye-23c8d2e5
UPDATE campaigns SET slug = 'paraf-platinum-ve-parafly-platinum-dan-amazon-prime-uyeligi-hediye-halkbank' WHERE id = 9985; -- Was: paraf-platinum-ve-parafly-platinum-dan-amazon-prime-uyeligi-hediye-f06579ff
UPDATE campaigns SET slug = 'lastik-com-trde-bridgestone-ve-lassa-urunlerinde-10-indirim-akbank' WHERE id = 14143; -- Was: lastik-com-trde-bridgestone-ve-lassa-urunlerinde-10-indirim-3
UPDATE campaigns SET slug = 'lastik-com-trde-bridgestone-ve-lassa-urunlerinde-10-indirim-akbank-wings' WHERE id = 14654; -- Was: lastik-com-trde-bridgestone-ve-lassa-urunlerinde-10-indirim-2
UPDATE campaigns SET slug = 'garanti-bbva-posu-olan-okullarda-pesin-odemelerinize-faizsiz-6-taksit-garanti-bbva' WHERE id = 14382; -- Was: garanti-bbva-posu-olan-okullarda-pesin-odemelerinize-faizsiz-6-taksit-2
UPDATE campaigns SET slug = 'ramseyde-5-taksit-garanti-bbva' WHERE id = 9897; -- Was: ramseyde-5-taksit-2
UPDATE campaigns SET slug = 'enterprise-da-bmw-x3-benzinli-otomatik-4490-tl-kiralama-ayricaligi-garanti-bbva' WHERE id = 16535; -- Was: enterprise-da-bmw-x3-benzinli-otomatik-4490-tl-kiralama-ayricaligi-2
UPDATE campaigns SET slug = 'nautica-da-4-taksit-garanti-bbva' WHERE id = 9721; -- Was: nautica-da-4-taksit-2
UPDATE campaigns SET slug = 'lacoste-ta-4-taksit-garanti-bbva' WHERE id = 9701; -- Was: lacoste-ta-4-taksit-2
UPDATE campaigns SET slug = 'secili-e-ticaret-alisverislerinize-1-500-tl-parafpara' WHERE id = 14879; -- Was: secili-e-ticaret-alisverislerinize-1-500-tl-parafpara-8677db80
UPDATE campaigns SET slug = 'secili-e-ticaret-alisverislerinize-1-500-tl-parafpara-halkbank' WHERE id = 15730; -- Was: secili-e-ticaret-alisverislerinize-1-500-tl-parafpara-0c8e1467
UPDATE campaigns SET slug = 'konfor-mobilyada-400-tl-chip-para-ve-9-taksit-firsati-akbank' WHERE id = 15367; -- Was: konfor-mobilyada-400-tl-chip-para-ve-9-taksit-firsati-2
UPDATE campaigns SET slug = 'jumbo-da-pesin-fiyatina-6-aya-varan-taksit-garanti-bbva' WHERE id = 9675; -- Was: jumbo-da-pesin-fiyatina-6-aya-varan-taksit-2
UPDATE campaigns SET slug = 'trendyol-da-9-taksit-garanti-bbva' WHERE id = 16180; -- Was: trendyol-da-9-taksit-2
UPDATE campaigns SET slug = 'trendyol-da-6-taksit-garanti-bbva' WHERE id = 15563; -- Was: trendyol-da-6-taksit-2
UPDATE campaigns SET slug = 'intemada-9-aya-varan-taksit-firsati-akbank' WHERE id = 8193; -- Was: intemada-9-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'hastane-ve-eczane-odemelerinize-ucretsiz-2-taksit-firsati-garanti-bbva' WHERE id = 15468; -- Was: hastane-ve-eczane-odemelerinize-ucretsiz-2-taksit-firsati-2
UPDATE campaigns SET slug = 'hastane-ve-eczane-odemelerinize-ucretsiz-2-taksit-firsati-garanti-bbva-garanti-miles-smiles' WHERE id = 15520; -- Was: hastane-ve-eczane-odemelerinize-ucretsiz-2-taksit-firsati-3
UPDATE campaigns SET slug = 'my-visalilara-yurt-disi-restoran-harcamalarinda-30-nakit-iade-garanti-bbva' WHERE id = 9650; -- Was: my-visalilara-yurt-disi-restoran-harcamalarinda-30-nakit-iade-2
UPDATE campaigns SET slug = 'my-visalilara-yurt-disi-restoran-harcamalarinda-30-nakit-iade-garanti-bbva-garanti-bonus' WHERE id = 9980; -- Was: my-visalilara-yurt-disi-restoran-harcamalarinda-30-nakit-iade-3
UPDATE campaigns SET slug = 'yemeksepetinde-375-tlye-varan-chip-para-firsati-akbank' WHERE id = 14678; -- Was: yemeksepetinde-375-tlye-varan-chip-para-firsati-2
UPDATE campaigns SET slug = 'heartbeat-te-4-taksit-garanti-bbva' WHERE id = 9641; -- Was: heartbeat-te-4-taksit-2
UPDATE campaigns SET slug = 'fakir-alisverislerinizde-9-taksit-firsati-sizi-bekliyor-akbank' WHERE id = 14099; -- Was: fakir-alisverislerinizde-9-taksit-firsati-sizi-bekliyor-2
UPDATE campaigns SET slug = 'secili-okullarda-taksit-firsati-garanti-bbva' WHERE id = 15491; -- Was: secili-okullarda-taksit-firsati-2
UPDATE campaigns SET slug = 'secili-okullarda-taksit-firsati-garanti-bbva-garanti-miles-smiles' WHERE id = 15553; -- Was: secili-okullarda-taksit-firsati-3
UPDATE campaigns SET slug = 'a101-ekstra-da-700-tl-ye-varan-maxipuan-i-sbankasi' WHERE id = 15687; -- Was: a101-ekstra-da-700-tl-ye-varan-maxipuan-1
UPDATE campaigns SET slug = 'market-ve-gida-alisverislerinize-1-000-tlye-varan-chip-para-akbank' WHERE id = 14028; -- Was: market-ve-gida-alisverislerinize-1-000-tlye-varan-chip-para-2
UPDATE campaigns SET slug = 'gant-te-4-taksit-garanti-bbva' WHERE id = 9633; -- Was: gant-te-4-taksit-2
UPDATE campaigns SET slug = 'u-s-polo-assn-de-6-taksit-garanti-bbva' WHERE id = 9619; -- Was: u-s-polo-assn-de-6-taksit-2
UPDATE campaigns SET slug = 'u-s-polo-assn-de-6-taksit-garanti-bbva-garanti-miles-smiles' WHERE id = 9790; -- Was: u-s-polo-assn-de-6-taksit-3
UPDATE campaigns SET slug = 'bridgestoneda-6-aya-varan-taksit-firsati-akbank' WHERE id = 16494; -- Was: bridgestoneda-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'teknosada-18-000-tl-ve-uzeri-harcamaya-1-000-tl-chip-para-akbank' WHERE id = 16495; -- Was: teknosada-18-000-tl-ve-uzeri-harcamaya-1-000-tl-chip-para-2
UPDATE campaigns SET slug = 'teknosada-18-000-tl-ve-uzeri-harcamaya-1-000-tl-chip-para-akbank-wings' WHERE id = 16499; -- Was: teknosada-18-000-tl-ve-uzeri-harcamaya-1-000-tl-chip-para-3
UPDATE campaigns SET slug = 'mitsubishi-electric-klimada-pesin-fiyatina-8-taksit-garanti-bbva' WHERE id = 15538; -- Was: mitsubishi-electric-klimada-pesin-fiyatina-8-taksit-2
UPDATE campaigns SET slug = 'mitsubishi-electric-klimada-pesin-fiyatina-8-taksit-garanti-bbva-garanti-bonus' WHERE id = 15697; -- Was: mitsubishi-electric-klimada-pesin-fiyatina-8-taksit-3
UPDATE campaigns SET slug = 'garanti-bbva-pos-u-olan-okullarda-pesin-odemelerinize-faizsiz-6-taksit-garanti-bbva' WHERE id = 15510; -- Was: garanti-bbva-pos-u-olan-okullarda-pesin-odemelerinize-faizsiz-6-taksit-2
UPDATE campaigns SET slug = 'kip-te-5-taksit-garanti-bbva' WHERE id = 9692; -- Was: kip-te-5-taksit-2
UPDATE campaigns SET slug = 'cacharel-de-6-taksit-garanti-bbva' WHERE id = 9570; -- Was: cacharel-de-6-taksit-2
UPDATE campaigns SET slug = 'tohum-otizm-vakfi-bagislarinda-chip-paralariniz-5-kat-degerleniyor-akbank' WHERE id = 16497; -- Was: tohum-otizm-vakfi-bagislarinda-chip-paralariniz-5-kat-degerleniyor-2
UPDATE campaigns SET slug = 'karaca-grup-ta-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9682; -- Was: karaca-grup-ta-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'yolcu360tan-garanti-bbvalilara-ozel-yurt-disinda-15-indirim-garanti-bbva' WHERE id = 9183; -- Was: yolcu360tan-garanti-bbvalilara-ozel-yurt-disinda-15-indirim-2
UPDATE campaigns SET slug = 'yolcu360tan-garanti-bbvalilara-ozel-yurt-disinda-15-indirim-garanti-bbva-garanti-bonus' WHERE id = 9566; -- Was: yolcu360tan-garanti-bbvalilara-ozel-yurt-disinda-15-indirim-3
UPDATE campaigns SET slug = 'teknosada-vade-farksiz-6-aya-varan-taksit-firsati-akbank' WHERE id = 11079; -- Was: teknosada-vade-farksiz-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'paraf-genci-z-ile-giyim-kozmetik-elektronik-harcamalarina-600-tl-parafpara' WHERE id = 12986; -- Was: paraf-genci-z-ile-giyim-kozmetik-elektronik-harcamalarina-600-tl-parafpara-61888248
UPDATE campaigns SET slug = 'paraf-genci-z-ile-giyim-kozmetik-elektronik-harcamalarina-600-tl-parafpara-halkbank' WHERE id = 14759; -- Was: paraf-genci-z-ile-giyim-kozmetik-elektronik-harcamalarina-600-tl-parafpara-9e594cc3
UPDATE campaigns SET slug = 'fashfed-de-4-taksit-garanti-bbva' WHERE id = 9623; -- Was: fashfed-de-4-taksit-2
UPDATE campaigns SET slug = 'renault-servis-kampanyasi-totalenergies' WHERE id = 16884; -- Was: renault-servis-kampanyasi-2
UPDATE campaigns SET slug = 'paraf-ile-totalenergies-istasyonlarinda-400-tl-parafpara-totalenergies' WHERE id = 16883; -- Was: paraf-ile-totalenergies-istasyonlarinda-400-tl-parafpara-2
UPDATE campaigns SET slug = 'evidea-da-pesin-fiyatina-4-taksit-firsati-garanti-bbva' WHERE id = 15504; -- Was: evidea-da-pesin-fiyatina-4-taksit-firsati-2
UPDATE campaigns SET slug = 'beymen-business-ta-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9502; -- Was: beymen-business-ta-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'tatilbudur-da-7-500-tl-ye-varan-worldpuan-vakifbank' WHERE id = 16588; -- Was: tatilbudur-da-7-500-tl-ye-varan-worldpuan-1
UPDATE campaigns SET slug = '2-000-tl-1-000-000-tl-arasi-dijital-gib-gov-tr-den-yapilan-gelir-vergisi-odemelerinize-3-taksit-garanti-bbva' WHERE id = 15477; -- Was: 2-000-tl-1-000-000-tl-arasi-dijital-gib-gov-tr-den-yapilan-gelir-vergisi-odemelerinize-3-taksit-2
UPDATE campaigns SET slug = 'boyner-de-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9531; -- Was: boyner-de-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'nazar-profiterol-de-15-i-ndirim' WHERE id = 9447; -- Was: nazar-profiterol-de-15-i-ndirim-610f520f
UPDATE campaigns SET slug = 'nazar-profiterol-de-15-i-ndirim-halkbank' WHERE id = 10162; -- Was: nazar-profiterol-de-15-i-ndirim-1339de88
UPDATE campaigns SET slug = 'market-alisverislerinize-1-250-tl-parafpara' WHERE id = 14752; -- Was: market-alisverislerinize-1-250-tl-parafpara-561492ec
UPDATE campaigns SET slug = 'market-alisverislerinize-1-250-tl-parafpara-halkbank' WHERE id = 15708; -- Was: market-alisverislerinize-1-250-tl-parafpara-7f770b74
UPDATE campaigns SET slug = 'd-s-damat-ta-6-aya-varan-taksit-firsati' WHERE id = 9431; -- Was: d-s-damat-ta-6-aya-varan-taksit-firsati-244b3f17
UPDATE campaigns SET slug = 'd-s-damat-ta-6-aya-varan-taksit-firsati-halkbank' WHERE id = 10125; -- Was: d-s-damat-ta-6-aya-varan-taksit-firsati-7dbc7e84
UPDATE campaigns SET slug = 'ataturk-kultur-merkezi' WHERE id = 16233; -- Was: ataturk-kultur-merkezi-34ce6bcb
UPDATE campaigns SET slug = 'ataturk-kultur-merkezi-turk-telekom' WHERE id = 16234; -- Was: ataturk-kultur-merkezi-476acede
UPDATE campaigns SET slug = 'yatas-bedding-de-taksit-firsatlari-garanti-bbva' WHERE id = 9425; -- Was: yatas-bedding-de-taksit-firsatlari-2
UPDATE campaigns SET slug = 'idefix' WHERE id = 12687; -- Was: idefix-1000
UPDATE campaigns SET slug = 'idefix-turk-telekom' WHERE id = 16228; -- Was: idefix-7e454c98
UPDATE campaigns SET slug = 'puffy-de-taksit-firsatlari-garanti-bbva' WHERE id = 9410; -- Was: puffy-de-taksit-firsatlari-2
UPDATE campaigns SET slug = 'pazarama-tatilde-10-000-tlye-varan-indirim-firsati-akbank' WHERE id = 14257; -- Was: pazarama-tatilde-10-000-tlye-varan-indirim-firsati-3
UPDATE campaigns SET slug = 'pazarama-tatilde-10-000-tlye-varan-indirim-firsati-akbank-wings' WHERE id = 15374; -- Was: pazarama-tatilde-10-000-tlye-varan-indirim-firsati-2
UPDATE campaigns SET slug = 'amazon-com-trde-pesin-fiyatina-9-aya-varan-taksit-firsati' WHERE id = 14282; -- Was: amazon-com-trde-pesin-fiyatina-9-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'amazon-com-trde-pesin-fiyatina-9-aya-varan-taksit-firsati-akbank' WHERE id = 14723; -- Was: amazon-com-trde-pesin-fiyatina-9-aya-varan-taksit-firsati
UPDATE campaigns SET slug = 'lassa-bridgestone-dan-totalenergies-istasyonlarinda-gecerli-2-500-tl-ye-varan-yakit-puan-hediye-totalenergies' WHERE id = 16882; -- Was: lassa-bridgestone-dan-totalenergies-istasyonlarinda-gecerli-2-500-tl-ye-varan-yakit-puan-hediye-2
UPDATE campaigns SET slug = 'daniel-wellington-alisverislerinde-7-aya-varan-taksit-firsati-akbank' WHERE id = 16014; -- Was: daniel-wellington-alisverislerinde-7-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'enza-home-da-taksit-firsatlari-garanti-bbva' WHERE id = 9389; -- Was: enza-home-da-taksit-firsatlari-2
UPDATE campaigns SET slug = 'vakkorama-da-5-taksit-firsati' WHERE id = 16643; -- Was: vakkorama-da-5-taksit-firsati-44a4f2ae
UPDATE campaigns SET slug = 'vakkorama-da-5-taksit-firsati-halkbank' WHERE id = 16645; -- Was: vakkorama-da-5-taksit-firsati-92d8bcef
UPDATE campaigns SET slug = 'opet-kampanyasi-opet' WHERE id = 16406; -- Was: opet-kampanyasi-2
UPDATE campaigns SET slug = 'opet-kampanyasi-opet-opet-kart' WHERE id = 16745; -- Was: opet-kampanyasi-3
UPDATE campaigns SET slug = 'opet-kampanyasi-opet-opet-kart-akaryakit' WHERE id = 16746; -- Was: opet-kampanyasi-4
UPDATE campaigns SET slug = 'the-moose-bayde-20-000-tl-uzeri-alisverise-800-tl-chip-para-akbank' WHERE id = 14680; -- Was: the-moose-bayde-20-000-tl-uzeri-alisverise-800-tl-chip-para-2
UPDATE campaigns SET slug = 'divanev-de-taksit-firsatlari-garanti-bbva' WHERE id = 9375; -- Was: divanev-de-taksit-firsatlari-2
UPDATE campaigns SET slug = 'arkadasini-davet-et-25-tlye-varan-yakit-puan-kazan-totalenergies' WHERE id = 16760; -- Was: arkadasini-davet-et-25-tlye-varan-yakit-puan-kazan-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disinda-yapacaginiz-alisverislerde-toplamda-2500-mart' WHERE id = 12544; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disinda-yapacaginiz-alisverislerde-toplamda-2500-mart-2026
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disinda-yapacaginiz-alisverislerde-toplamda-2500-mart-yapi-kredi' WHERE id = 12552; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disinda-yapacaginiz-alisverislerde-toplamda-2500-mart-2026-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disinda-yapacaginiz-alisverislerde-toplamda-2500-mart-yapi-kredi-world' WHERE id = 12565; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disinda-yapacaginiz-alisverislerde-toplamda-2500-mart-2026-3
UPDATE campaigns SET slug = 'boyner-de-4-000-tl-ve-uzeri-alisverislerde-400-tl-indirim-garanti-bbva' WHERE id = 15454; -- Was: boyner-de-4-000-tl-ve-uzeri-alisverislerde-400-tl-indirim-2
UPDATE campaigns SET slug = 'goz-balik-restoran-da-10-indirim-ayricaligi-garanti-bbva' WHERE id = 9159; -- Was: goz-balik-restoran-da-10-indirim-ayricaligi-2
UPDATE campaigns SET slug = 'hepsiburada-alisverislerinde-300-tlye-varan-chip-para-akbank' WHERE id = 14635; -- Was: hepsiburada-alisverislerinde-300-tlye-varan-chip-para-2
UPDATE campaigns SET slug = 'easy-point-te-10-indirim-ayricaligi-garanti-bbva' WHERE id = 9142; -- Was: easy-point-te-10-indirim-ayricaligi-2
UPDATE campaigns SET slug = 'amiri-de-10-indirim-ayricaligi-garanti-bbva' WHERE id = 15449; -- Was: amiri-de-10-indirim-ayricaligi-2
UPDATE campaigns SET slug = 'garanti-bbva-troy-logolu-temassiz-kartlarla-yapilan-ilk-ulasim-odemesi-ucretsiz-garanti-bbva' WHERE id = 15441; -- Was: garanti-bbva-troy-logolu-temassiz-kartlarla-yapilan-ilk-ulasim-odemesi-ucretsiz-2
UPDATE campaigns SET slug = 'garanti-bbva-troy-logolu-temassiz-kartlarla-yapilan-ilk-ulasim-odemesi-ucretsiz-garanti-bbva-garanti-bonus' WHERE id = 15444; -- Was: garanti-bbva-troy-logolu-temassiz-kartlarla-yapilan-ilk-ulasim-odemesi-ucretsiz-3
UPDATE campaigns SET slug = 'garanti-bbva-troy-logolu-temassiz-kartlarla-yapilan-ilk-ulasim-odemesi-ucretsiz-garanti-bbva-garanti-bonus-ulasim' WHERE id = 15448; -- Was: garanti-bbva-troy-logolu-temassiz-kartlarla-yapilan-ilk-ulasim-odemesi-ucretsiz-4
UPDATE campaigns SET slug = 'kipte-5-taksit-garanti-bbva' WHERE id = 9893; -- Was: kipte-5-taksit-2
UPDATE campaigns SET slug = '5-nisan-avukatlar-gunune-ozel-10-000-tl-ve-uzeri-alisveriste-ekstra-15-indirim-garanti-bbva' WHERE id = 15440; -- Was: 5-nisan-avukatlar-gunune-ozel-10-000-tl-ve-uzeri-alisveriste-ekstra-15-indirim-2
UPDATE campaigns SET slug = 'enterprise-da-35-indirim-garanti-bbva' WHERE id = 9170; -- Was: enterprise-da-35-indirim-2
UPDATE campaigns SET slug = 'budget-ta-arac-kiralamalarinda-35-indirim-garanti-bbva' WHERE id = 9148; -- Was: budget-ta-arac-kiralamalarinda-35-indirim-2
UPDATE campaigns SET slug = 'konyali-saat-alisverislerinde-7-aya-varan-taksit-firsati-akbank' WHERE id = 16016; -- Was: konyali-saat-alisverislerinde-7-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'enuygun-comda-7-500-tlye-varan-chip-para-firsati-akbank' WHERE id = 12141; -- Was: enuygun-comda-7-500-tlye-varan-chip-para-firsati-2
UPDATE campaigns SET slug = 'gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan' WHERE id = 14923; -- Was: gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan-2026
UPDATE campaigns SET slug = 'gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan-yapi-kredi' WHERE id = 14941; -- Was: gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan-2026-2
UPDATE campaigns SET slug = 'gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan-yapi-kredi-crystal' WHERE id = 14944; -- Was: gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan-2026-3
UPDATE campaigns SET slug = 'gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan-yapi-kredi-world' WHERE id = 15061; -- Was: gida-marketi-alisverislerinize-600-tl-world-pay-ile-odemelerde-ek-150-tl-toplamda-750-tly-nisan-2026-4
UPDATE campaigns SET slug = 'silver-logolu-paraf-mastercard-iniza-ozel-boyner-de-1-000-tl-indirim' WHERE id = 12104; -- Was: silver-logolu-paraf-mastercard-iniza-ozel-boyner-de-1-000-tl-indirim-44a5cd90
UPDATE campaigns SET slug = 'silver-logolu-paraf-mastercard-iniza-ozel-boyner-de-1-000-tl-indirim-halkbank' WHERE id = 12107; -- Was: silver-logolu-paraf-mastercard-iniza-ozel-boyner-de-1-000-tl-indirim-75fe9044
UPDATE campaigns SET slug = 'windycar-arac-kiralamalarinda-35-indirim-garanti-bbva' WHERE id = 9135; -- Was: windycar-arac-kiralamalarinda-35-indirim-2
UPDATE campaigns SET slug = 'masterpass-hesabinizi-world-paye-ekledikten-sonraki-ilk-tr-karekod-harcamaniza-250-tl-puan-yapi-kredi' WHERE id = 11966; -- Was: masterpass-hesabinizi-world-paye-ekledikten-sonraki-ilk-tr-karekod-harcamaniza-250-tl-puan-2
UPDATE campaigns SET slug = 'enuygunda-juzdan-ile-odeye-7-500-tlye-varan-chip-para-akbank' WHERE id = 11870; -- Was: enuygunda-juzdan-ile-odeye-7-500-tlye-varan-chip-para-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-cevrimici-muzik-oyun-ve-video-platformlarindan-yapacaginiz' WHERE id = 16414; -- Was: mastercard-logolu-asil-kartiniz-ile-cevrimici-muzik-oyun-ve-video-platformlarindan-yapacaginiz-2026
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-cevrimici-muzik-oyun-ve-video-platformlarindan-yapacaginiz-yapi-kredi' WHERE id = 16417; -- Was: mastercard-logolu-asil-kartiniz-ile-cevrimici-muzik-oyun-ve-video-platformlarindan-yapacaginiz-2026-2
UPDATE campaigns SET slug = 'vestelde-axess-ile-pesin-fiyatina-9-taksit-firsati' WHERE id = 14150; -- Was: vestelde-axess-ile-pesin-fiyatina-9-taksit-firsati-2
UPDATE campaigns SET slug = 'vestelde-axess-ile-pesin-fiyatina-9-taksit-firsati-akbank' WHERE id = 14672; -- Was: vestelde-axess-ile-pesin-fiyatina-9-taksit-firsati
UPDATE campaigns SET slug = 'paraf-troy-temassiz-kartiniz-ile-canakkale-de-hafta-ici-her-gun-ilk-toplu-tasima-ulasim-odemesi-ucretsiz' WHERE id = 15948; -- Was: paraf-troy-temassiz-kartiniz-ile-canakkale-de-hafta-ici-her-gun-ilk-toplu-tasima-ulasim-odemesi-ucretsiz-5c453f49
UPDATE campaigns SET slug = 'paraf-troy-temassiz-kartiniz-ile-canakkale-de-hafta-ici-her-gun-ilk-toplu-tasima-ulasim-odemesi-ucretsiz-halkbank' WHERE id = 15956; -- Was: paraf-troy-temassiz-kartiniz-ile-canakkale-de-hafta-ici-her-gun-ilk-toplu-tasima-ulasim-odemesi-ucretsiz-a67181d3
UPDATE campaigns SET slug = 'amazon-com-tr-de-pesin-fiyatina-9-taksit-firsati-garanti-bbva' WHERE id = 15488; -- Was: amazon-com-tr-de-pesin-fiyatina-9-taksit-firsati-2
UPDATE campaigns SET slug = 'dyson-alisverislerinizde-pesin-fiyatina-9-taksit-firsati-akbank' WHERE id = 14147; -- Was: dyson-alisverislerinizde-pesin-fiyatina-9-taksit-firsati-3
UPDATE campaigns SET slug = 'carrefoursa-da-pesin-fiyatina-5-aya-varan-taksit-garanti-bbva' WHERE id = 15495; -- Was: carrefoursa-da-pesin-fiyatina-5-aya-varan-taksit-2
UPDATE campaigns SET slug = 'tatilsepetinde-juzdan-ile-odeye-7-500-tlye-varan-chip-para-akbank' WHERE id = 14064; -- Was: tatilsepetinde-juzdan-ile-odeye-7-500-tlye-varan-chip-para-2
UPDATE campaigns SET slug = 'trendyolda-pesin-fiyatina-3-ve-6-taksit-firsati-akbank' WHERE id = 14291; -- Was: trendyolda-pesin-fiyatina-3-ve-6-taksit-firsati-2
UPDATE campaigns SET slug = 'goodyear-da-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 15514; -- Was: goodyear-da-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'nurus-ta-pesin-fiyatina-7-taksit-garanti-bbva' WHERE id = 15469; -- Was: nurus-ta-pesin-fiyatina-7-taksit-2
UPDATE campaigns SET slug = 'tatilsepetinde-vade-farksiz-9-aya-varan-taksit-firsati-akbank' WHERE id = 14279; -- Was: tatilsepetinde-vade-farksiz-9-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'sahibinden-com-yepyde-pesin-fiyatina-9-aya-varan-taksit-firsati-akbank' WHERE id = 14242; -- Was: sahibinden-com-yepyde-pesin-fiyatina-9-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'kale-de-9-taksit-kolayligi-garanti-bbva' WHERE id = 15528; -- Was: kale-de-9-taksit-kolayligi-2
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-yurt-disi-duty-freelerde-15-indirim-firsati' WHERE id = 14916; -- Was: silver-logolu-mastercardiniza-ozel-yurt-disi-duty-freelerde-15-indirim-firsati-2025
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-yurt-disi-duty-freelerde-15-indirim-firsati-yapi-kredi' WHERE id = 14971; -- Was: silver-logolu-mastercardiniza-ozel-yurt-disi-duty-freelerde-15-indirim-firsati
UPDATE campaigns SET slug = 'pazarama-da-worldpuan-lar-n-z-3-kat-de-erli-harcay-n-vakifbank' WHERE id = 12739; -- Was: pazarama-da-worldpuan-lar-n-z-3-kat-de-erli-harcay-n-1
UPDATE campaigns SET slug = 'beauty-omelettede-10-000-tl-ve-uzeri-islemlerde-4-taksit-garanti-bbva' WHERE id = 11312; -- Was: beauty-omelettede-10-000-tl-ve-uzeri-islemlerde-4-taksit-2
UPDATE campaigns SET slug = 'beauty-omelettede-10-000-tl-ve-uzeri-islemlerde-4-taksit-garanti-bbva-garanti-shop-fly' WHERE id = 11313; -- Was: beauty-omelettede-10-000-tl-ve-uzeri-islemlerde-4-taksit-3
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-duty-freelerde-toplamda-1500-tlye-varan-mart' WHERE id = 12542; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-duty-freelerde-toplamda-1500-tlye-varan-mart-2026
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-duty-freelerde-toplamda-1500-tlye-varan-mart-yapi-kredi' WHERE id = 12548; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-duty-freelerde-toplamda-1500-tlye-varan-mart-2026-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-duty-freelerde-toplamda-1500-tlye-varan-mart-yapi-kredi-world' WHERE id = 12563; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-duty-freelerde-toplamda-1500-tlye-varan-mart-2026-3
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-yurt-disi-restoran-ve-kafe-odemelerinde-15-indirim' WHERE id = 14913; -- Was: silver-logolu-mastercardiniza-ozel-yurt-disi-restoran-ve-kafe-odemelerinde-15-indirim-2025
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-yurt-disi-restoran-ve-kafe-odemelerinde-15-indirim-yapi-kredi' WHERE id = 14951; -- Was: silver-logolu-mastercardiniza-ozel-yurt-disi-restoran-ve-kafe-odemelerinde-15-indirim-2025-2
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-yurt-disi-restoran-ve-kafe-odemelerinde-15-indirim-yapi-kredi-world' WHERE id = 14969; -- Was: silver-logolu-mastercardiniza-ozel-yurt-disi-restoran-ve-kafe-odemelerinde-15-indirim
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-fiziki-poslardan-toplamda-yapacaginiz-3-mart' WHERE id = 12540; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-fiziki-poslardan-toplamda-yapacaginiz-3-mart-2026
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-fiziki-poslardan-toplamda-yapacaginiz-3-mart-yapi-kredi' WHERE id = 12547; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-fiziki-poslardan-toplamda-yapacaginiz-3-mart-2026-2
UPDATE campaigns SET slug = 'mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-fiziki-poslardan-toplamda-yapacaginiz-3-mart-yapi-kredi-world' WHERE id = 12558; -- Was: mastercard-logolu-asil-kartiniz-ile-yurt-disindaki-fiziki-poslardan-toplamda-yapacaginiz-3-mart-2026-3
UPDATE campaigns SET slug = 'elektronik-ve-beyaz-esya-alisverislerinize-2-500-tl-ye-varan-parafpara' WHERE id = 14857; -- Was: elektronik-ve-beyaz-esya-alisverislerinize-2-500-tl-ye-varan-parafpara-15c02080
UPDATE campaigns SET slug = 'elektronik-ve-beyaz-esya-alisverislerinize-2-500-tl-ye-varan-parafpara-halkbank' WHERE id = 15782; -- Was: elektronik-ve-beyaz-esya-alisverislerinize-2-500-tl-ye-varan-parafpara-025162a9
UPDATE campaigns SET slug = 'trendyol-go-by-uber-eats-ten-yemek-siparisinize-ek-20-indirim-garanti-bbva' WHERE id = 15864; -- Was: trendyol-go-by-uber-eats-ten-yemek-siparisinize-ek-20-indirim-2
UPDATE campaigns SET slug = 'scorpions-konser-biletleri-15-i-ndirimli-i-sbankasi' WHERE id = 10927; -- Was: scorpions-konser-biletleri-15-i-ndirimli-1
UPDATE campaigns SET slug = 'avvada-5-taksit-garanti-bbva' WHERE id = 9903; -- Was: avvada-5-taksit-2
UPDATE campaigns SET slug = 'kenan-dogulu-symphonity-konserlerinde-15-indirim-firsati-akbank' WHERE id = 16009; -- Was: kenan-dogulu-symphonity-konserlerinde-15-indirim-firsati-2
UPDATE campaigns SET slug = 'gant-com-tr-de-1-500-tl-i-ndirim-ziraat-bankasi' WHERE id = 15136; -- Was: gant-com-tr-de-1-500-tl-i-ndirim-1
UPDATE campaigns SET slug = 'rotap-saatte-6-aya-varan-taksit-firsati-akbank' WHERE id = 8120; -- Was: rotap-saatte-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'puma-da-6-taksit-garanti-bbva' WHERE id = 9750; -- Was: puma-da-6-taksit-2
UPDATE campaigns SET slug = 'bonus-platinum-visa-ve-shop-fly-visaya-ozel-tazemasada-400-tl-indirim-garanti-bbva' WHERE id = 12529; -- Was: bonus-platinum-visa-ve-shop-fly-visaya-ozel-tazemasada-400-tl-indirim-2
UPDATE campaigns SET slug = 'avva-da-5-taksit-garanti-bbva' WHERE id = 9465; -- Was: avva-da-5-taksit-2
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-galataportta-otopark-1-tl-yapi-kredi' WHERE id = 14966; -- Was: silver-logolu-mastercardiniza-ozel-galataportta-otopark-1-tl-2
UPDATE campaigns SET slug = 'superstep-te-4-taksit-garanti-bbva' WHERE id = 9769; -- Was: superstep-te-4-taksit-2
UPDATE campaigns SET slug = 'ramsey-de-5-taksit-garanti-bbva' WHERE id = 9759; -- Was: ramsey-de-5-taksit-2
UPDATE campaigns SET slug = 'istanbulkart-turkiye-finans' WHERE id = 14933; -- Was: istanbulkart-1775075810
UPDATE campaigns SET slug = 'ikea-aile-ile-9-taksit-firsati-garanti-bbva' WHERE id = 9806; -- Was: ikea-aile-ile-9-taksit-firsati-2
UPDATE campaigns SET slug = 'ikea-aile-ile-9-taksit-firsati-garanti-bbva-garanti-bonus' WHERE id = 10104; -- Was: ikea-aile-ile-9-taksit-firsati-3
UPDATE campaigns SET slug = 'hilmi-yildirim-zeytinyaglari-nda-10-i-ndirim' WHERE id = 11389; -- Was: hilmi-yildirim-zeytinyaglari-nda-10-i-ndirim-612e8c8c
UPDATE campaigns SET slug = 'hilmi-yildirim-zeytinyaglari-nda-10-i-ndirim-halkbank' WHERE id = 11408; -- Was: hilmi-yildirim-zeytinyaglari-nda-10-i-ndirim-90362698
UPDATE campaigns SET slug = 'defacto-da-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9591; -- Was: defacto-da-pesin-fiyatina-6-taksit-2
UPDATE campaigns SET slug = 'ds-damatta-6-aya-varan-taksit-firsati-akbank' WHERE id = 8205; -- Was: ds-damatta-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'taksidepos-kampanyasi' WHERE id = 9510; -- Was: taksidepos-kampanyasi-c9a9e8cd
UPDATE campaigns SET slug = 'taksidepos-kampanyasi-halkbank' WHERE id = 10182; -- Was: taksidepos-kampanyasi-6c65386f
UPDATE campaigns SET slug = 'silver-logolu-mastercardiniza-ozel-raffles-istanbulda-15-indirim-and-spada-20-indirim-firsati-yapi-kredi' WHERE id = 9086; -- Was: silver-logolu-mastercardiniza-ozel-raffles-istanbulda-15-indirim-and-spada-20-indirim-firsati-2
UPDATE campaigns SET slug = 'almira-hotel-restoranlarinda-aninda-indirim-ayricaligi-garanti-bbva' WHERE id = 9164; -- Was: almira-hotel-restoranlarinda-aninda-indirim-ayricaligi-2
UPDATE campaigns SET slug = 'almira-hotel-restoranlarinda-aninda-indirim-ayricaligi-garanti-bbva-garanti-bonus' WHERE id = 10031; -- Was: almira-hotel-restoranlarinda-aninda-indirim-ayricaligi-3
UPDATE campaigns SET slug = 'teknosa-da-pesin-fiyatina-6-aya-varan-taksit-firsati-garanti-bbva' WHERE id = 9415; -- Was: teknosa-da-pesin-fiyatina-6-aya-varan-taksit-firsati-2
UPDATE campaigns SET slug = 'yargici-da-6-taksit-garanti-bbva' WHERE id = 9797; -- Was: yargici-da-6-taksit-2
UPDATE campaigns SET slug = 'armagan-oyuncakta-4-taksit-garanti-bbva' WHERE id = 9647; -- Was: armagan-oyuncakta-4-taksit-2
UPDATE campaigns SET slug = 'lee-ve-wrangler-da-pesin-fiyatina-6-taksit-garanti-bbva' WHERE id = 9711; -- Was: lee-ve-wrangler-da-pesin-fiyatina-6-taksit-2